// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewMoviewFunc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewMoviewFunc));
        
        string IMigrationMetadata.Id
        {
            get { return "202007241910371_NewMoviewFunc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
